openapi: 3.0.1
info:
  description: This is the API documentation for the Parodos Workflow Service. It
    provides operations to execute assessments to determine infrastructure options
    (tooling + environments). Also executes infrastructure task workflows to call
    downstream systems to stand-up an infrastructure option.
  title: Parodos Workflow Service API
  version: v1.0.0
servers:
- description: Generated server url
  url: http://localhost:8080
tags:
- description: Login endpoint
  name: Login
- description: Operations about workflow
  name: Workflow
- description: Operations about project
  name: Project
- description: Operations about workflow definition
  name: Workflow Definition
- description: Operations about project access
  name: Project Access
paths:
  /api/v1/login:
    get:
      operationId: login
      responses:
        "200":
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Login
      tags:
      - Login
      x-accepts: '*/*'
  /api/v1/projects:
    get:
      operationId: getProjects
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ProjectResponseDTO'
                type: array
          description: Succeeded
        "304":
          description: Not Modified
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns a list of project
      tags:
      - Project
      x-accepts: application/json
    post:
      operationId: createProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectRequestDTO'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponseDTO'
          description: Created
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Creates a new project
      tags:
      - Project
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/projects/access/{id}/status:
    get:
      operationId: getProjectAccessStatus
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessStatusResponseDTO'
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content: {}
          description: Not found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns status about a specified project access request
      tags:
      - Project Access
      x-accepts: application/json
    post:
      operationId: updateProjectAccessStatus
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessStatusRequestDTO'
        required: true
      responses:
        "204":
          description: Updated successfully
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content: {}
          description: Not found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Update status of a specified project access request
      tags:
      - Project Access
      x-content-type: application/json
      x-accepts: '*/*'
  /api/v1/projects/{id}:
    get:
      operationId: getProjectById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponseDTO'
          description: Succeeded
        "304":
          description: Not Modified
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content: {}
          description: Not found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns information about a specified project
      tags:
      - Project
      x-accepts: application/json
  /api/v1/projects/{id}/access:
    post:
      operationId: createAccessRequestToProject
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessRequestDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessResponseDTO'
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content: {}
          description: Not found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Request user access to project
      tags:
      - Project
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/projects/{id}/users:
    delete:
      operationId: removeUsersFromProject
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              items:
                type: string
              type: array
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectUserRoleResponseDTO'
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content: {}
          description: Not found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Remove users from project
      tags:
      - Project
      x-content-type: application/json
      x-accepts: application/json
    post:
      operationId: updateUserRolesToProject
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/UserRoleRequestDTO'
              type: array
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectUserRoleResponseDTO'
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content: {}
          description: Not found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Update user roles in project
      tags:
      - Project
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/workflowdefinitions:
    get:
      operationId: getWorkFlowDefinitions
      parameters:
      - explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/WorkFlowDefinitionResponseDTO'
                type: array
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns a list of workflow definition
      tags:
      - Workflow Definition
      x-accepts: application/json
  /api/v1/workflowdefinitions/{id}:
    get:
      operationId: getWorkFlowDefinitionById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkFlowDefinitionResponseDTO'
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          content: {}
          description: Not found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns information about a workflow definition by id
      tags:
      - Workflow Definition
      x-accepts: application/json
  /api/v1/workflowdefinitions/{workflowDefinitionName}/parameters/update/{valueProviderName}:
    post:
      operationId: updateParameter
      parameters:
      - description: workflow Definition Name
        example: complexWorkFlow
        explode: false
        in: path
        name: workflowDefinitionName
        required: true
        schema:
          type: string
        style: simple
      - description: "valueProvider Name. It can be referenced to 'valueProviderName'\
          \ in [GET /getWorkFlowDefinitions](#/Workflow%20Definition/getWorkFlowDefinitions)"
        example: complexWorkFlowValueProvider
        explode: false
        in: path
        name: valueProviderName
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/WorkParameterValueRequestDTO'
              type: array
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/WorkParameterValueResponseDTO'
                type: array
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns updated parameter value
      tags:
      - Workflow Definition
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/workflows:
    get:
      operationId: getStatusByProjectId
      parameters:
      - explode: true
        in: query
        name: projectId
        required: false
        schema:
          format: uuid
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/WorkFlowResponseDTO'
                type: array
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns workflows by project id
      tags:
      - Workflow
      x-accepts: application/json
    post:
      operationId: execute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkFlowRequestDTO'
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkFlowExecutionResponseDTO'
          description: Accepted
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Executes a workflow
      tags:
      - Workflow
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/workflows/{workFlowExecutionId}/checkers/{workFlowCheckerTaskName}:
    post:
      operationId: updateWorkFlowCheckerTaskStatus
      parameters:
      - explode: false
        in: path
        name: workFlowExecutionId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: false
        in: path
        name: workFlowCheckerTaskName
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkFlowCheckerTaskRequestDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content: {}
          description: Not found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Updates a workflow checker task status
      tags:
      - Workflow
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/workflows/{workFlowExecutionId}/context:
    get:
      operationId: getWorkflowParameters
      parameters:
      - explode: false
        in: path
        name: workFlowExecutionId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: param
        required: true
        schema:
          items:
            enum:
            - ID
            - NAME
            - PARAMETERS
            - ARGUMENTS
            - STATUS
            - WORKFLOW_OPTIONS
            - PARENT_WORKFLOW
            - ADDITIONAL_INFO
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkFlowContextResponseDTO'
          description: Succeeded
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns workflow context parameters
      tags:
      - Workflow
      x-accepts: application/json
  /api/v1/workflows/{workFlowExecutionId}/log:
    get:
      operationId: getLog
      parameters:
      - explode: false
        in: path
        name: workFlowExecutionId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: taskName
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: Succeeded
        "304":
          description: Not Modified
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns workflow execution log
      tags:
      - Workflow
      x-accepts: "*/*,text/plain"
  /api/v1/workflows/{workFlowExecutionId}/restart:
    post:
      operationId: restartWorkFlow
      parameters:
      - explode: false
        in: path
        name: workFlowExecutionId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkFlowExecutionResponseDTO'
          description: Accepted
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content: {}
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Restart a workflow execution with same parameters
      tags:
      - Workflow
      x-accepts: application/json
  /api/v1/workflows/{workFlowExecutionId}/status:
    get:
      operationId: getStatus
      parameters:
      - explode: false
        in: path
        name: workFlowExecutionId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkFlowStatusResponseDTO'
          description: Succeeded
        "304":
          description: Not Modified
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Not Found
        "409":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Conflict
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDTO'
          description: Internal Server Error
      summary: Returns a workflow status
      tags:
      - Workflow
      x-accepts: application/json
components:
  schemas:
    AccessRequestDTO:
      example:
        role: OWNER
        username: username
      properties:
        role:
          enum:
          - OWNER
          - DEVELOPER
          - ADMIN
          type: string
        username:
          type: string
      type: object
    AccessResponseDTO:
      example:
        approvalSentTo:
        - approvalSentTo
        - approvalSentTo
        accessRequestId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        escalationSentTo: escalationSentTo
        project:
          createdDate: 2000-01-23T04:56:07.000+00:00
          createdBy: createdBy
          name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        accessRequestId:
          format: uuid
          type: string
        approvalSentTo:
          items:
            type: string
          type: array
        escalationSentTo:
          type: string
        project:
          $ref: '#/components/schemas/ProjectDTO'
      type: object
    AccessStatusRequestDTO:
      example:
        comment: comment
        status: APPROVED
      properties:
        comment:
          type: string
        status:
          enum:
          - APPROVED
          - PENDING
          - REJECTED
          type: string
      type: object
    AccessStatusResponseDTO:
      example:
        accessRequestId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        status: APPROVED
      properties:
        accessRequestId:
          format: uuid
          type: string
        status:
          enum:
          - APPROVED
          - PENDING
          - REJECTED
          type: string
      type: object
    AdditionalInfo:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    ArgumentRequestDTO:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    ErrorMessageDTO:
      properties:
        date:
          format: date-time
          type: string
        description:
          type: string
        message:
          type: string
        status:
          format: int32
          type: integer
      type: object
    ProjectDTO:
      example:
        createdDate: 2000-01-23T04:56:07.000+00:00
        createdBy: createdBy
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        createdBy:
          type: string
        createdDate:
          format: date-time
          type: string
        id:
          format: uuid
          type: string
        name:
          type: string
      type: object
    ProjectRequestDTO:
      example:
        name: name
        description: description
      properties:
        description:
          type: string
        name:
          type: string
      type: object
    ProjectResponseDTO:
      example:
        createdDate: 2000-01-23T04:56:07.000+00:00
        createdBy: createdBy
        accessRole: accessRole
        modifiedDate: 2000-01-23T04:56:07.000+00:00
        name: name
        description: description
        modifiedBy: modifiedBy
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        accessRole:
          type: string
        createdBy:
          type: string
        createdDate:
          format: date-time
          type: string
        description:
          type: string
        id:
          format: uuid
          type: string
        modifiedBy:
          type: string
        modifiedDate:
          format: date-time
          type: string
        name:
          type: string
      type: object
    ProjectUserRoleResponseDTO:
      example:
        userResponseDTOList:
        - roles:
          - OWNER
          - OWNER
          username: username
        - roles:
          - OWNER
          - OWNER
          username: username
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        projectName: projectName
      properties:
        id:
          format: uuid
          type: string
        projectName:
          type: string
        userResponseDTOList:
          items:
            $ref: '#/components/schemas/UserRoleResponseDTO'
          type: array
      type: object
    UserRoleRequestDTO:
      example:
        roles:
        - OWNER
        - OWNER
        username: username
      properties:
        roles:
          items:
            enum:
            - OWNER
            - DEVELOPER
            - ADMIN
            type: string
          type: array
        username:
          type: string
      type: object
    UserRoleResponseDTO:
      example:
        roles:
        - OWNER
        - OWNER
        username: username
      properties:
        roles:
          items:
            enum:
            - OWNER
            - DEVELOPER
            - ADMIN
            type: string
          type: array
          uniqueItems: true
        username:
          type: string
      type: object
    WorkDefinitionResponseDTO:
      example:
        outputs:
        - EXCEPTION
        - EXCEPTION
        processingType: SEQUENTIAL
        works:
        - null
        - null
        author: author
        name: name
        workType: TASK
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        parameters:
          key:
            key: "{}"
      properties:
        author:
          type: string
        id:
          format: uuid
          type: string
        name:
          type: string
        outputs:
          items:
            enum:
            - EXCEPTION
            - HTTP2XX
            - NO_EXCEPTION
            - OTHER
            type: string
          type: array
        parameters:
          additionalProperties:
            additionalProperties:
              type: object
            type: object
          type: object
        processingType:
          enum:
          - SEQUENTIAL
          - PARALLEL
          - OTHER
          type: string
        workType:
          enum:
          - TASK
          - WORKFLOW
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkDefinitionResponseDTO'
          type: array
      type: object
    WorkFlowCheckerTaskRequestDTO:
      example:
        status: FAILED
      properties:
        status:
          enum:
          - FAILED
          - COMPLETED
          - IN_PROGRESS
          - REJECTED
          - PENDING
          type: string
      type: object
    WorkFlowContextResponseDTO:
      example:
        workFlowOptions:
          continuationOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          upgradeOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          newOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          migrationOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          otherOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
          currentVersion:
            identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
            recommended: true
        workFlowExecutionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        workFlowExecutionId:
          format: uuid
          type: string
        workFlowOptions:
          $ref: '#/components/schemas/WorkFlowOptionsResponseDTO'
      type: object
    WorkFlowDefinitionResponseDTO:
      example:
        processingType: SEQUENTIAL
        works:
        - outputs:
          - EXCEPTION
          - EXCEPTION
          processingType: SEQUENTIAL
          works:
          - null
          - null
          author: author
          name: name
          workType: TASK
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          parameters:
            key:
              key: "{}"
        - outputs:
          - EXCEPTION
          - EXCEPTION
          processingType: SEQUENTIAL
          works:
          - null
          - null
          author: author
          name: name
          workType: TASK
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          parameters:
            key:
              key: "{}"
        modifyDate: 2000-01-23T04:56:07.000+00:00
        author: author
        fallbackWorkflow: fallbackWorkflow
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: ASSESSMENT
        parameters:
          key:
            key: "{}"
        properties:
          version: version
        createDate: 2000-01-23T04:56:07.000+00:00
      properties:
        author:
          type: string
        createDate:
          format: date-time
          type: string
        fallbackWorkflow:
          type: string
        id:
          format: uuid
          type: string
        modifyDate:
          format: date-time
          type: string
        name:
          type: string
        parameters:
          additionalProperties:
            additionalProperties:
              type: object
            type: object
          type: object
        processingType:
          enum:
          - SEQUENTIAL
          - PARALLEL
          - OTHER
          type: string
        properties:
          $ref: '#/components/schemas/WorkFlowPropertiesDefinitionDTO'
        type:
          enum:
          - ASSESSMENT
          - CHECKER
          - INFRASTRUCTURE
          - ESCALATION
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkDefinitionResponseDTO'
          type: array
      type: object
    WorkFlowExecutionResponseDTO:
      example:
        workStatus: FAILED
        workFlowExecutionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        workFlowExecutionId:
          format: uuid
          type: string
        workStatus:
          enum:
          - FAILED
          - COMPLETED
          - IN_PROGRESS
          - REJECTED
          - PENDING
          type: string
      type: object
    WorkFlowOption:
      example:
        identifier: identifier
        workFlowName: workFlowName
        displayName: displayName
        description: description
        details:
        - details
        - details
        recommended: true
      properties:
        description:
          type: string
        details:
          items:
            type: string
          type: array
        displayName:
          type: string
        identifier:
          type: string
        recommended:
          type: boolean
        workFlowName:
          type: string
      type: object
    WorkFlowOptionsResponseDTO:
      example:
        continuationOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        upgradeOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        newOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        migrationOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        otherOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
        currentVersion:
          identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
          recommended: true
      properties:
        continuationOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        currentVersion:
          $ref: '#/components/schemas/WorkFlowOption'
        migrationOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        newOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        otherOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        upgradeOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
      type: object
    WorkFlowPropertiesDefinitionDTO:
      example:
        version: version
      properties:
        version:
          type: string
      type: object
    WorkFlowRequestDTO:
      example:
        workFlowName: workFlowName
        invokingExecutionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        works:
        - works:
          - null
          - null
          arguments:
          - value: value
            key: key
          - value: value
            key: key
          type: TASK
          workName: workName
        - works:
          - null
          - null
          arguments:
          - value: value
            key: key
          - value: value
            key: key
          type: TASK
          workName: workName
        arguments:
        - value: value
          key: key
        - value: value
          key: key
        projectId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        arguments:
          items:
            $ref: '#/components/schemas/ArgumentRequestDTO'
          type: array
        invokingExecutionId:
          format: uuid
          type: string
        projectId:
          format: uuid
          type: string
        workFlowName:
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkRequestDTO'
          type: array
      type: object
    WorkFlowResponseDTO:
      example:
        workStatus: FAILED
        additionalInfos:
        - value: value
          key: key
        - value: value
          key: key
        workFlowName: workFlowName
        executeBy: executeBy
        endDate: endDate
        workFlowExecutionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        workFlowType: ASSESSMENT
        projectId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        startDate: startDate
      properties:
        additionalInfos:
          items:
            $ref: '#/components/schemas/AdditionalInfo'
          type: array
        endDate:
          type: string
        executeBy:
          type: string
        projectId:
          format: uuid
          type: string
        startDate:
          type: string
        workFlowExecutionId:
          format: uuid
          type: string
        workFlowName:
          type: string
        workFlowType:
          enum:
          - ASSESSMENT
          - CHECKER
          - INFRASTRUCTURE
          - ESCALATION
          type: string
        workStatus:
          enum:
          - FAILED
          - COMPLETED
          - IN_PROGRESS
          - REJECTED
          - PENDING
          type: string
      type: object
    WorkFlowStatusResponseDTO:
      example:
        originalExecutionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        workFlowName: workFlowName
        works:
        - alertMessage: alertMessage
          works:
          - null
          - null
          name: name
          message: message
          type: TASK
          status: FAILED
        - alertMessage: alertMessage
          works:
          - null
          - null
          name: name
          message: message
          type: TASK
          status: FAILED
        workFlowExecutionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        restartedCount: 0
        message: message
        fallbackExecutionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        status: FAILED
      properties:
        fallbackExecutionId:
          format: uuid
          type: string
        message:
          type: string
        originalExecutionId:
          format: uuid
          type: string
        restartedCount:
          format: int32
          type: integer
        status:
          enum:
          - FAILED
          - COMPLETED
          - IN_PROGRESS
          - REJECTED
          - PENDING
          type: string
        workFlowExecutionId:
          format: uuid
          type: string
        workFlowName:
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkStatusResponseDTO'
          type: array
      type: object
    WorkParameterValueRequestDTO:
      example:
        workName: workName
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
        workName:
          type: string
      required:
      - key
      type: object
    WorkParameterValueResponseDTO:
      example:
        options:
        - options
        - options
        propertyPath: propertyPath
        value: value
        key: key
      properties:
        key:
          type: string
        options:
          items:
            type: string
          type: array
        propertyPath:
          type: string
        value:
          type: string
      type: object
    WorkRequestDTO:
      example:
        works:
        - null
        - null
        arguments:
        - value: value
          key: key
        - value: value
          key: key
        type: TASK
        workName: workName
      properties:
        arguments:
          items:
            $ref: '#/components/schemas/ArgumentRequestDTO'
          type: array
        type:
          enum:
          - TASK
          - WORKFLOW
          type: string
        workName:
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkRequestDTO'
          type: array
      type: object
    WorkStatusResponseDTO:
      example:
        alertMessage: alertMessage
        works:
        - null
        - null
        name: name
        message: message
        type: TASK
        status: FAILED
      properties:
        alertMessage:
          type: string
        message:
          type: string
        name:
          type: string
        status:
          enum:
          - FAILED
          - COMPLETED
          - IN_PROGRESS
          - REJECTED
          - PENDING
          type: string
        type:
          enum:
          - TASK
          - WORKFLOW
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkStatusResponseDTO'
          type: array
      type: object

